<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubKategoriSeeder7 extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subCategories = [];

        // 500.10 ENERGI DAN SUMBER DAYA MINERAL
        $categoryId46 = DB::table('categories')
            ->where('nomor_kategori', '500.10')
            ->value('id');

        $subCategories = array_merge($subCategories, [
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '6.8', 'nama_sub_kategori' => 'Rencana Kebutuhan Impor Barang (RKIB) dan Rencana Impor Barang (RIB)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7', 'nama_sub_kategori' => 'Pembinaan Usaha Hulu Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.1', 'nama_sub_kategori' => 'Penyiapan dan Penawaran Wilayah Kerja (WK) Minyak dan Gas Bumi (Konvensional dan Non Konvensional)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.2', 'nama_sub_kategori' => 'Eksplorasi Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.3', 'nama_sub_kategori' => 'Eksploitasi Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.4', 'nama_sub_kategori' => 'Pengembangan lapangan Minyak dan Gas Bumi (POD)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.5', 'nama_sub_kategori' => 'Perpanjangan Kontrak KKS'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.6', 'nama_sub_kategori' => 'Penetapan Alokasi dan Harga Gas'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.7', 'nama_sub_kategori' => 'Partisipasi Interest'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '7.8', 'nama_sub_kategori' => 'Tumpang Tindih Lahan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '8', 'nama_sub_kategori' => 'Pembinaan Usaha Hilir Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '8.1', 'nama_sub_kategori' => 'Perumusan pedoman, prosedur, layanan serta pengawasan Usaha Pengolahan, Pengangkutan, Penyimpanan, dan Niaga Minyak Bumi dan Gas Bumi, Hasil Olahan dan Bahan Bakar Lain'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '8.2', 'nama_sub_kategori' => 'Fasilitasi dan pertimbangan pelanggaran'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '8.3', 'nama_sub_kategori' => 'Penetapan Harga dan Subsidi Bahan Bakar yang ditetapkan dengan Keputusan Menteri'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9', 'nama_sub_kategori' => 'Teknik dan Lingkungan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.1', 'nama_sub_kategori' => 'Perumusan pelaksanaan dan pengawasan Standar Nasional Indonesia (SNI) / Standar Kompetensi Kerja Nasional Indonesia (SKKNI)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.2', 'nama_sub_kategori' => 'Registrasi Nomor Pelumas Terdaftar (NPT)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.3', 'nama_sub_kategori' => 'Buku Register Welding Procedure Specification (WPS)/ Procedure Qualification Record (PQR)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.4', 'nama_sub_kategori' => 'Register dan Sertifikat Kualifikasi Juru Las'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.5', 'nama_sub_kategori' => 'Keselamatan Hulu Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.6', 'nama_sub_kategori' => 'Keselamatan Hilir Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.7', 'nama_sub_kategori' => 'Keselamatan Kerja dan Lindungan Lingkungan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.8', 'nama_sub_kategori' => 'Dokumen Persetujuan Penunjukkan Kepala/Wakil Kepala Teknik Tambang Hulu dan Hilir'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.9', 'nama_sub_kategori' => 'Penghargaan Keselamatan Kerja'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '9.10', 'nama_sub_kategori' => 'Usaha penunjang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '10', 'nama_sub_kategori' => 'Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '10.1', 'nama_sub_kategori' => 'Perencanaan Program Kerja Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '10.2', 'nama_sub_kategori' => 'Pengadaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '10.3', 'nama_sub_kategori' => 'Pelaksanaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '10.4', 'nama_sub_kategori' => 'Pengawasan dan Evaluasi Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11', 'nama_sub_kategori' => 'Penyiapan Program Energi Terbarukan dan Konservasi Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.1', 'nama_sub_kategori' => 'Usulan Wilayah Kerja Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.2', 'nama_sub_kategori' => 'Usul Program Aneka Energi Pemerintah Daerah dan Lembaga'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.3', 'nama_sub_kategori' => 'Penyiapan Program Pemanfaatan Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.4', 'nama_sub_kategori' => 'Proyeksi Kebutuhan Energi dari EBT'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.5', 'nama_sub_kategori' => 'Perencanaan Pemanfaatan Energi dari EBT'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.6', 'nama_sub_kategori' => 'Penyusunan Neraca Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '11.7', 'nama_sub_kategori' => 'Road Map di Bidang EBT'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12', 'nama_sub_kategori' => 'Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.1', 'nama_sub_kategori' => 'Penerbitan Surat Keterangan Terdaftar (SKT)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.2', 'nama_sub_kategori' => 'Sertifikasi Kelayakan Penggunaan Instalasi (SKPI)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.3', 'nama_sub_kategori' => 'Sertifikasi Kelayakan Penggunaan Peralatan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.4', 'nama_sub_kategori' => 'Rekomendasi Bahan Peledak'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.5', 'nama_sub_kategori' => 'Perizinan penggunaan gudang bahan peledak'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.6', 'nama_sub_kategori' => 'Izin Tangki Bahan Bakar Cair'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.7', 'nama_sub_kategori' => 'Persetujuan sertifikasi Welding Procedure Specification (WPS) dan Procedure Qualification Record (PQR) dan kualifikasi Juru Las'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.8', 'nama_sub_kategori' => 'Penerbitan Izin Usaha Panas Bumi (IUP)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.9', 'nama_sub_kategori' => 'Penerbitan Izin Panas Bumi (IPB)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.10', 'nama_sub_kategori' => 'Penerbitan Izin Pemanfaatan Langsung (IPL)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.11', 'nama_sub_kategori' => 'Penetapan kapasitas usaha panas bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.12', 'nama_sub_kategori' => 'Penetapan kapasitas Pembangkit Listrik Tenaga Panas Bumi (PLTP)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.13', 'nama_sub_kategori' => 'Pengawasan Eksplorasi dan Eksploitasi Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.14', 'nama_sub_kategori' => 'Pelaksanaan Kerja Sama Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.15', 'nama_sub_kategori' => 'Inventarisasi, Verifikasi dan Evaluasi Obvitnas Bidang Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.16', 'nama_sub_kategori' => 'Monitoring Pelaksanaan Program Pengembangan dan Pemberdayaan Masyarakat (PPM) pada Kegiatan Pengusahaan Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '12.17', 'nama_sub_kategori' => 'Pembinaan dan Pengawasan Investasi Panas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13', 'nama_sub_kategori' => 'Bioenergi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.1', 'nama_sub_kategori' => 'Penerbitan Izin Usaha Niaga Bahan Bakar Nabati (BNN)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.2', 'nama_sub_kategori' => 'Pengadaan Bahan Bakar Nabati (BBN)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.3', 'nama_sub_kategori' => 'Penerbitan Rekomendasi Ekspor - Impor'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.4', 'nama_sub_kategori' => 'Penetapan Indeks Harga Pasar BBN (HIP BBN)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.5', 'nama_sub_kategori' => 'Evaluasi/Revisi HIP BBN'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.6', 'nama_sub_kategori' => 'Database Pengusahaan Bioenergi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.7', 'nama_sub_kategori' => 'Penetapan Badan Usaha sebagai Pengelola Energi Biomassa atau Biogas untuk Pembangkit Listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.8', 'nama_sub_kategori' => 'Penetapan Spesifikasi Bahan Bakar Nabati'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '13.9', 'nama_sub_kategori' => 'Usul Program Bioenergi Pemerintah Daerah dan Lembaga'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14', 'nama_sub_kategori' => 'Aneka Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14.1', 'nama_sub_kategori' => 'Penerbitan Izin Usaha Aneka Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14.2', 'nama_sub_kategori' => 'Penetapan Kapasitas Usaha'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14.3', 'nama_sub_kategori' => 'Rekomendasi Kompetensi dan Rencana Penggunaan Tenaga Kerja Asing'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14.4', 'nama_sub_kategori' => 'Rekomendasi Persetujuan Perubahan Pemegang Saham'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '14.5', 'nama_sub_kategori' => 'Persetujuan Rencana Impor Barang (RIB)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15', 'nama_sub_kategori' => 'Konservasi Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.1', 'nama_sub_kategori' => 'Audit Energi melalui program kemitraan Konservasi Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.2', 'nama_sub_kategori' => 'Monitoring Implementasi hasil audit energi melalui program kemitraan konservasi energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.3', 'nama_sub_kategori' => 'Pembinaan dan pengawasan pelaksanaan manajamen energi di pengguna energi di atas 6.000 TOE'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.4', 'nama_sub_kategori' => 'Pengawasan sertifikasi label dan tanda hemat energi pada lampu swabalast'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.5', 'nama_sub_kategori' => 'Penyusunan daftar peralatan/teknologi efisiensi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.6', 'nama_sub_kategori' => 'Penyusunan emisi energi gas rumah kaca'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.7', 'nama_sub_kategori' => 'Pemberian insentif dan disinsentif konservasi energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.8', 'nama_sub_kategori' => 'Profil investasi efisiensi energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.9', 'nama_sub_kategori' => 'Invesment Grade Audit (IGA)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '15.10', 'nama_sub_kategori' => 'Bimbingan Teknis Bidang EBTKE'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '16', 'nama_sub_kategori' => 'Perencanaan dan Pembangunan Infrastruktur EBTKE'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '16.1', 'nama_sub_kategori' => 'Usul Pembangunan Infrastruktur Pemerintah Daerah dan Lembaga'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '16.2', 'nama_sub_kategori' => 'Perencanaan Pembangunan Infrastruktur Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '16.3', 'nama_sub_kategori' => 'Pelaksanaan Pembangunan Infrastruktur Bidang EBTKE'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '16.4', 'nama_sub_kategori' => 'Evaluasi Program Kerja'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '17', 'nama_sub_kategori' => 'Bina Program Tenaga Listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '17.1', 'nama_sub_kategori' => 'Investasi dan pendanaan tenaga listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '17.2', 'nama_sub_kategori' => 'Pengembangan listrik pedesaan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '17.3', 'nama_sub_kategori' => 'Data dan Informasi Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '18', 'nama_sub_kategori' => 'Bina Usaha Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '18.1', 'nama_sub_kategori' => 'Penyiapan Usaha Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '18.2', 'nama_sub_kategori' => 'Harga dan Subsidi Listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '18.3', 'nama_sub_kategori' => 'Hubungan komersial tenaga listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '18.4', 'nama_sub_kategori' => 'Perlindungan konsumen listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '19', 'nama_sub_kategori' => 'Teknik dan Lingkungan Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '19.1', 'nama_sub_kategori' => 'Kelaikan teknik dan keselamatan ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '19.2', 'nama_sub_kategori' => 'Penyiapan kompetensi dan pengawasan tenaga teknik ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '19.3', 'nama_sub_kategori' => 'Usaha penunjang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '19.4', 'nama_sub_kategori' => 'Perlindungan lingkungan ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20', 'nama_sub_kategori' => 'Sertifikasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20.1', 'nama_sub_kategori' => 'Dokumen Sertifikasi Produk peralatan dan pemanfaatan tenaga listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20.2', 'nama_sub_kategori' => 'Dokumen Penunjukan Lembaga Sertifikasi Kompetensi (LSK)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20.3', 'nama_sub_kategori' => 'Dokumen Penerbitan Sertifikasi Laik Operasi (SLO) Instalasi Tenaga Listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20.4', 'nama_sub_kategori' => 'Dokumen Pembinaan dan pengawasan sertifikat laik operasi (SLO) instalasi tenaga listrik'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '20.5', 'nama_sub_kategori' => 'Registrasi Sertifikasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '21', 'nama_sub_kategori' => 'Akreditasi Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '22', 'nama_sub_kategori' => 'Standarisasi Kompetensi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '23', 'nama_sub_kategori' => 'Standardisasi Nasional Indonesia (SNI) Bidang Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '23.1', 'nama_sub_kategori' => 'Perumusan rancangan SNI bidang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '23.2', 'nama_sub_kategori' => 'Forum konsensus rancangan SNI bidang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '23.3', 'nama_sub_kategori' => 'Program pemberlakuan SNI wajib bidang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '23.4', 'nama_sub_kategori' => 'Dokumen pengawasan penerapan SNI wajib bidang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24', 'nama_sub_kategori' => 'Standardisasi Usaha Penunjang Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24.1', 'nama_sub_kategori' => 'Klasifikasi usaha penunjang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24.2', 'nama_sub_kategori' => 'Kualifikasi usaha penunjang ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24.3', 'nama_sub_kategori' => 'Dokumen penunjukan LIT (Lembaga Inspeksi Teknis)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24.4', 'nama_sub_kategori' => 'Laporan berkala pemegang penunjukan LIT'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '24.5', 'nama_sub_kategori' => 'Laporan hasil pengawasan penunjukan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25', 'nama_sub_kategori' => 'Bina Program Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.1', 'nama_sub_kategori' => 'Penyiapan dan Perencanaan Program Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.2', 'nama_sub_kategori' => 'Rencana Induk Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.3', 'nama_sub_kategori' => 'Pengembangan Investasi dan Kerja Sama Bidang Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.4', 'nama_sub_kategori' => 'Data dan Informasai Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.5', 'nama_sub_kategori' => 'Pelaporan Program Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.6', 'nama_sub_kategori' => 'Perencanaan, Penyiapan dan Penawaran Wilayah Kerja (WK) Mineral dan Batubara melalui lelang reguler'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.7', 'nama_sub_kategori' => 'Data dan Informasi Wilayah Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.8', 'nama_sub_kategori' => 'Perencanaan Produksi Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '25.9', 'nama_sub_kategori' => 'Pengembangan dan Pemanfaatan Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26', 'nama_sub_kategori' => 'Pembinaan Pengusahaan Mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.1', 'nama_sub_kategori' => 'Ketenagakerjaan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.2', 'nama_sub_kategori' => 'Pemberdayaan masyarakat sekitar tambang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.3', 'nama_sub_kategori' => 'Penyelesaian perselisihan usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.4', 'nama_sub_kategori' => 'Rekomendasi kegiatan usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.5', 'nama_sub_kategori' => 'Laporan/data kegiatan eksplorasi mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.6', 'nama_sub_kategori' => 'Pengawasan produksi dan pemasaran mineral (logam, bukan logam batuan, radioaktif, dan mineral jarang)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.7', 'nama_sub_kategori' => 'Perizinan usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.8', 'nama_sub_kategori' => 'Kontrak Karya (KK)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.9', 'nama_sub_kategori' => 'Pengelolaan barang Kontrak Karya (KK)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.10', 'nama_sub_kategori' => 'Persetujuan Obyek Vital Nasional (OBVITNAS)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.11', 'nama_sub_kategori' => 'Persetujuan perubahan saham direksi, komisaris, pada perusahaan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.12', 'nama_sub_kategori' => 'Teguran kepada pengusahan Kontrak Karya (KK)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.13', 'nama_sub_kategori' => 'Tanggapan kepada pemerintah daerah terkait usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.14', 'nama_sub_kategori' => 'Pedoman/petunjuk teknis pertambangan mineral termasuk rancangan awal sampul dengan rancangan akhir'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.15', 'nama_sub_kategori' => 'Pelaporan usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.16', 'nama_sub_kategori' => 'Penghargaan usaha pertambangan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '26.17', 'nama_sub_kategori' => 'Penerbitan sertifikat clear and clean (CnC) Izin Usaha Pertambangan (IUP) Mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27', 'nama_sub_kategori' => 'Pembinaan Pengusahaan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.1', 'nama_sub_kategori' => 'Ketenagakerjaan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.2', 'nama_sub_kategori' => 'Pemberdayaan masyarakat sekitar tambang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.3', 'nama_sub_kategori' => 'Penyelesaian perselisihan usaha pertambangan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.4', 'nama_sub_kategori' => 'Rekomendasi kegiatan usaha pertambangan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.5', 'nama_sub_kategori' => 'Laporan/data kegiatan eksplorasi batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.6', 'nama_sub_kategori' => 'Pengawasan produksi dan pemasaran batubara (bitumen padat, batuan aspal, batubara dan gambut)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.7', 'nama_sub_kategori' => 'Perizinan Usaha Pertambangan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.8', 'nama_sub_kategori' => 'Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.9', 'nama_sub_kategori' => 'Pengelolaan Barang Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.10', 'nama_sub_kategori' => 'Persetujuan Obyek Vital Nasional (OBVITNAS)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.11', 'nama_sub_kategori' => 'Persetujuan perubahan saham direksi, komisaris, pada perusahaan Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.12', 'nama_sub_kategori' => 'Teguran kepada pengusahan Perjanjian Karya Pengusahaan Batubara (PKP2B)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.13', 'nama_sub_kategori' => 'Tanggapan kepada pemerintah daerah terkait usaha pertambangan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.14', 'nama_sub_kategori' => 'Pedoman/petunjuk teknis pertambangan mineral termasuk rancangan awal sampul dengan rancangan akhir'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.15', 'nama_sub_kategori' => 'Pelaporan usaha pertambangan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.16', 'nama_sub_kategori' => 'Penghargaan usaha pertambangan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '27.17', 'nama_sub_kategori' => 'Penerbitan sertifikat clear and clean (CnC) Izin Usaha Pertambangan (IUP) Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '28', 'nama_sub_kategori' => 'Penerimaan Negara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '28.1', 'nama_sub_kategori' => 'Penerimaan Negara Bukan Pajak'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '28.2', 'nama_sub_kategori' => 'Penetapan Bagi Hasil Penerimaan Negara Bukan Pajak (PNBP)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '28.3', 'nama_sub_kategori' => 'Pelaksanaan Pemeriksaan dan Pengujian PNBP'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29', 'nama_sub_kategori' => 'Teknik dan Lingkungan Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.1', 'nama_sub_kategori' => 'Perumusan RSNI (Rancangan Standar Nasional Indonesia)/ RSKKNI (Rancangan Standar Kompetensi Kerja Nasional Indonesia)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.2', 'nama_sub_kategori' => 'Pengawasan Standardisasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.3', 'nama_sub_kategori' => 'Persetujuan Penunjukkan Kepala/Wakil Kepala Teknik Tambang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.4', 'nama_sub_kategori' => 'Pengawasan Keselamatan Kegiatan dan Keselamatan Pekerja'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.5', 'nama_sub_kategori' => 'Pemeriksaan teknis dan pengujian instalasi dan peralatan tambang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.6', 'nama_sub_kategori' => 'Analisis Mengenai Dampak Lingkungan (AMDAL)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.7', 'nama_sub_kategori' => 'Upaya Pengelolaan Lingkungan (UKL) dan Upaya Pemantauan Lingkungan (UPL)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.8', 'nama_sub_kategori' => 'Rekomendasi bahan kimia'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.9', 'nama_sub_kategori' => 'Pengawasan Pelaksanaan Pengelolaan dan Pemantauan Lingkungan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.10', 'nama_sub_kategori' => 'Laporan berkala teknik dan lingkungan pertambangan/ laporan tahunan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.11', 'nama_sub_kategori' => 'Pemberian Penghargaan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.12', 'nama_sub_kategori' => 'Pengawasan lingkungan pertambangan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.13', 'nama_sub_kategori' => 'Usaha Jasa Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.14', 'nama_sub_kategori' => 'Pembinaan dan pengawasan usaha jasa mineral dan batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.15', 'nama_sub_kategori' => 'Rekomendasi Teknis'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.16', 'nama_sub_kategori' => 'Persetujuan Teknis'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.17', 'nama_sub_kategori' => 'Pengawasan Teknis'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.18', 'nama_sub_kategori' => 'Pengawasan Konservasi Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '29.19', 'nama_sub_kategori' => 'Peminaan Teknik dan Lingkungan Mineral dan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30', 'nama_sub_kategori' => 'Program Penelitian dan Pengembangan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.1', 'nama_sub_kategori' => 'Rencana Penelitian dan Pengembangan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.2', 'nama_sub_kategori' => 'Pengembangan dan inovasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.3', 'nama_sub_kategori' => 'Dokumen penerapan/pemanfaatan/pendayagunaan/replikasi/prototipe hasil penelitian/pengkajian/pengembangan /inovasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.4', 'nama_sub_kategori' => 'Advokasi dan fasilitasi penelitian, pengembangan dan inovasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.5', 'nama_sub_kategori' => 'Diseminasi hasil penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.6', 'nama_sub_kategori' => 'Pembinaan penelitian/Pengembangan, pengkajian, dan penerapan ilmu pengetahunan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.7', 'nama_sub_kategori' => 'Jaringan Sistem Nasional Penelitian, Pengembangan dan Penerapan ilmu pengetahuan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.8', 'nama_sub_kategori' => 'Data dan informasi hasil penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.9', 'nama_sub_kategori' => 'Master proceeding/ jurnal penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.10', 'nama_sub_kategori' => 'Hak atas kekayaan intelektual (HaKI)'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.11', 'nama_sub_kategori' => 'Forum komunikasi penelitian, pengembangan dan penerapan ilmu pengetahuan dan teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.12', 'nama_sub_kategori' => 'Layanan jasa penelitian, pengembangan, penerapan IPTEK'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '30.13', 'nama_sub_kategori' => 'Sertifikasi personil peneliti bidang Sumber Daya Mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '31', 'nama_sub_kategori' => 'Sarana Litbang'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '31.1', 'nama_sub_kategori' => 'Administrasi penggunaan peralatan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '31.2', 'nama_sub_kategori' => 'Log-book Peralatan Survei/Peralatan Uji Kalibrasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '32', 'nama_sub_kategori' => 'Afiliasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '32.1', 'nama_sub_kategori' => 'Proyek Percontohan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '32.2', 'nama_sub_kategori' => 'Promosi dan Layanan Jasa Teknologi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '32.3', 'nama_sub_kategori' => 'Pembinaan Penelitian dan Pengembangan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '32.4', 'nama_sub_kategori' => 'Penyajian Informasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '33', 'nama_sub_kategori' => 'Penelitian dan Pengembangan Kegeologian'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '33.1', 'nama_sub_kategori' => 'Pemetaaan dan penelitian geologi, geokimia, dan geofisika kelautan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '33.2', 'nama_sub_kategori' => 'Energi Kelautan dan Kewilayahan Penelitian Energi dan kewilayahan pantai'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '33.3', 'nama_sub_kategori' => 'Penelitian sumber daya energi dan mineral kelautan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '33.4', 'nama_sub_kategori' => 'Penelitian Sumber Daya Mineral Kelautan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34', 'nama_sub_kategori' => 'Penelitian dan Pengembangan Teknologi Minyak dan Gas Bumi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.1', 'nama_sub_kategori' => 'Teknologi Eksplorasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.2', 'nama_sub_kategori' => 'Teknologi Eksploitasi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.3', 'nama_sub_kategori' => 'Laboratorium'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.4', 'nama_sub_kategori' => 'Study'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.5', 'nama_sub_kategori' => 'Teknologi Proses'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.6', 'nama_sub_kategori' => 'Teknologi Aplikasi Produk'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '34.7', 'nama_sub_kategori' => 'Teknologi Gas'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '35', 'nama_sub_kategori' => 'Penelitian dan Pengembangan Teknologi Mineral Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '35.1', 'nama_sub_kategori' => 'Teknologi Eksploitasi Tambang dan Pengolahan Sumber Daya'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '35.2', 'nama_sub_kategori' => 'Teknologi Pengolahan dan Pemanfaatan mineral'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '35.3', 'nama_sub_kategori' => 'Teknologi Pemanfaatan Batubara'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '36', 'nama_sub_kategori' => 'Penelitian dan Pengembangan Ketenagalistrikan dan Energi Baru Terbarukan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '36.1', 'nama_sub_kategori' => 'Energi baru terbarukan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '36.2', 'nama_sub_kategori' => 'Teknologi Ketenagalistrikan'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '36.3', 'nama_sub_kategori' => 'Lingkungan dan Konservasi Energi'],
            ['category_id' => $categoryId46, 'nomor_sub_kategori' => '36.4', 'nama_sub_kategori' => 'Penelitian dan Pengembangan Teknologi PLTSa (Pembangkit Listrik Tenaga Sampah) dan Konservasi Energi'],
        ]);

        // Insert data into the database
        DB::table('sub_kategoris')->insert($subCategories);
    }
}
